from __future__ import annotations

from typing import Any, Dict

from app.agents.base import BaseAgent
from app.llm.client import LLMClient, get_llm_client
from app.prompts.templates import PLANNER_SYSTEM_PROMPT


class PlannerAgent(BaseAgent):
    def __init__(self, llm: LLMClient | None = None) -> None:
        super().__init__(name="planner")
        self.llm = llm or get_llm_client()

    def run(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        goal = payload["goal"]
        context = payload.get("context", {})

        response = self.llm.complete_json(
            system_prompt=PLANNER_SYSTEM_PROMPT,
            user_payload={
                "task": "plan",
                "goal": goal,
                "context": context,
            },
        )

        steps = response.get("steps") or [
            "Understand the goal and available context",
            "Execute the main action for the goal",
            "Validate the execution result",
        ]

        return {
            "agent": self.name,
            "goal": goal,
            "steps": steps,
            "llm_provider": self.llm.provider_name,
            "reasoning": response.get("reasoning", "Plan generated by LLM provider"),
        }
